apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fluentd-py-api-svc
data:
  fluent.conf: |
    <source>
        @type tail
        path /app/logs/app.log
        pos_file /app/logs/app.log.pos
        tag app.logs
        <parse>
          @type regexp
          expression /^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3,6}) LEVEL=(?<level>\w+) MESSAGE=(?<message>.*)$/
          time_key timestamp
          time_format %Y-%m-%d %H:%M:%S.%L
        </parse>
    </source>

    <filter app.logs>
      @type record_transformer
      <record>
        service_name "py-api-svc"
      </record>
    </filter>

    <match app.logs>
      @type bigquery_insert
      
      <buffer>
        flush_mode immediate
      </buffer>
      
      #auth_method compute_engine
      auth_method json_key
      json_key /app/gcp-key/fluentd-ingress-jason-hsbc.json
      # private_key_passphrase notasecret # default

      project jason-hsbc
      dataset LOGS
      auto_create_table true
      table py-api-logs-v3

      <inject>
        time_key time_field_name
        time_type string
        time_format %Y-%m-%d %H:%M:%S
      </inject>

      schema [
        {
          "name": "timestamp",
          "type": "TIMESTAMP"
        },
        {
          "name": "service_name",
          "type": "STRING"
        },
        {
          "name": "level",
          "type": "STRING"
        },
        {
          "name": "message",
          "type": "STRING"
        }
      ]
    </match>
